#!/bin/bash

export POD_NAME=$1
export NAMESPACE=${2-default}
export INTERFACE=${3-"lo"}

if [[ -z ${POD_NAME} || -z ${NAMESPACE}   || -z ${INTERFACE} ]];
then
    echo "Some variables are missing"
    exit 1
else
    echo """Paramaters ;
        service: ${POD_NAME}
        branch: ${NAMESPACE}
        environment: ${INTERFACE}
    """
fi

kubectl debug -i ${POD_NAME} -n ${NAMESPACE} \
  --image emirozbir/tcpdumper:latest -- tcpdump -i ${INTERFACE} -w -