#!/bin/bash

set -e
export OS_VERSION=$(uname -a)
export DEBUG_CONTAINER_ID=$(echo $RANDOM)
export POD_NAME=$1
export NAMESPACE=$2
export INTERFACE=$3
export MODE=$4

if [[ -z ${POD_NAME} || -z ${NAMESPACE} || -z ${INTERFACE} ]];
then
    echo "WARNING some parameters are missing"
    exit 1
else
    echo """
        Parameters
        pod-name:  ${POD_NAME}
        namespace: ${NAMESPACE}
        interface: ${INTERFACE}
    """;
fi

if [[ "$OS_VERSION" == *"Darwin"* ]];
then
    export TCP_COMMAND="tcpdump -i ${INTERFACE} -w - "
else
    export TCP_COMMAND="tcpdump -U -i ${INTERFACE} -w - "
fi

kubectl debug -q -i ${POD_NAME} -n ${NAMESPACE} -c kshark-debugger-${DEBUG_CONTAINER_ID} \
    --image emirozbir/tcpdumper:latest -- ${TCP_COMMAND} | wireshark -k -i -